# Render Blueprint Configuration
# Deploy toàn bộ stack với 1 file

databases:
  - name: fullstack-mongo
    databaseName: fullstack
    user: fullstack_user
    plan: free
    ipAllowList: [] # Allow all IPs

services:
  # Backend API Service
  - type: web
    name: fullstack-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: fullstack-mongo
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        sync: false # Set này sau khi có frontend URL

  # Frontend Next.js Service
  - type: web
    name: fullstack-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false # Set này sau khi có backend URL
